---
title: "March 13th"
output: html_document
---

```{r}
library(PASWR2)
#Create a scatterplot to compare the two using a base function
plot(x = GRADES$sat, y = GRADES$gpa)
abline(lm(GRADES$gpa ~ GRADES$sat)) ## lm(y~x)
```

```{r}
#Same thing using ggplot
library(ggplot2)
ggplot(data = GRADES, aes(x = sat, y = gpa)) + ##sets up the axes
  geom_point() + ##plots the points
  geom_smooth(method = "lm") ##adds the line
```


```{r}
# Y = beta * x + Epsilon
#Create the model
mod <- lm(gpa ~ sat, data = GRADES)
X <- model.matrix(mod)
dim(X) #n by p aka 200 x 2
t(X) %*% X #gives the transpose, matrix multiplication, pxn * nxp = pxp
solve(t(X) %*% X) #gives the inverse

#preferred way to find (X'X)^-1 is summary(mod)$cov.unscaled where mod is defined above

BetaHat <- solve(t(X) %*% X) %*% t(X) %*% GRADES$gpa 
#Beta hat = (x'x)^-1 * x' * y, where x' means the transpose
BetaHat
#Beta hat ~ N(Beta, variance of Beta hat -> a matrix)
```

```{r}
#Co-Variance Matrix: variances on the diagonals and co-variances on non-diagonals
#Var(Beta Hat) = (X' * X)^-1 times mean squared error (MSE = Sum of Squared Errors SSE/(n-p)), SSE = sum (e_i)^2

#Finding SSE
anova(mod)
SSE <- anova(mod)[2,2]
SSE
MSE <- SSE/(200-2)
MSE

#Co-variance
MSE * solve(t(X) %*% X) #diagonals give beta and epsilon values

#take the square root of the matrix to find the standard deviation
(MSE * solve(t(X) %*% X))^0.5
```

```{r}
#(X'X)^-1 * (X'X) -> 2x2 identity matrix
solve(t(X) %*% X) %*% (t(X) %*% X)
```

```{r}
#95% CI for beta1
confint(mod, level = 0.95)

#"By Hand", book page 800
#b1 <- coef(summary(mod))[2,1]
#s.b1 <- coef(summary(mod))[2,2]
#ct <- qt(1 - 0.1/2, )
```

Wrestler example from page 794 of the book
```{r}
mod_2 <- lm(hwfat ~ abs + triceps, data = HSWRESTLER)
X <- model.matrix(mod_2)
head(X)
```

```{r}
#summary(mod_2)$cov.unscaled
#betaHat <- (solve(X' %*% X))
```

```{r} 
#page 801 12.37
#Sum of Squares due to Regression SSR
#Sum of Squared Errors SSE
#Sum of Squared Total SST


```














